spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mynotes
    username: mynotes
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: lesson_05
