#spring.application.name=myFirstProject

spring:
  profiles:
    #    active: local # ?????? @Profile(("")) - ? ?????? ?????? ?????? ??????? @Profile(("local")) ?? ?????? LocalEngine
    active: prod # ?????? @Profile(("")) - ? ?????? ?????? ?????? ??????? @Profile(("prod")) ?? ?????? ProdEngine